# Generated by Django 5.0 on 2024-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('player1_paddle_position', models.IntegerField(default=0)),
                ('player2_paddle_position', models.IntegerField(default=0)),
                ('ball_position', models.JSONField(default={'x': 0, 'y': 0})),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
            ],
        ),
    ]
