# Generated by Django 5.0.1 on 2024-02-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='name',
        ),
        migrations.AddField(
            model_name='tournament',
            name='kazanan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='oyuncu1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='oyuncu2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='oyuncu3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='yfinal',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
