# Generated by Django 5.0.1 on 2024-02-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_tournament_oyuncu1_alter_tournament_oyuncu2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='oyuncu1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='oyuncu2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='oyuncu3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
