# Generated by Django 5.0 on 2024-01-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_room_name_alter_room_ball_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ball_position',
            field=models.JSONField(default=dict),
        ),
    ]
