# Generated by Django 5.0.1 on 2024-02-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_tournament_oyuncu1_alter_tournament_oyuncu2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
