# Generated by Django 5.0 on 2024-02-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
    ]
