# Generated by Django 5.0 on 2023-12-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kisiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici', models.CharField(max_length=1000)),
                ('tam_adi', models.CharField(max_length=1000)),
                ('resim', models.ImageField(default='blog/img/7.jpg', upload_to='blogs')),
                ('toplam_mac', models.IntegerField(default=0)),
                ('zafer_mac', models.IntegerField(default=0)),
                ('bozgun_mac', models.IntegerField(default=0)),
                ('engel', models.BooleanField(default=True)),
                ('cevrimici', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
