# Generated by Django 5.0 on 2023-12-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engel',
            name='kisi',
            field=models.TextField(default=False),
        ),
    ]
