# Generated by Django 5.0 on 2023-12-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kisiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici', models.CharField(max_length=1000)),
                ('tam_adi', models.CharField(max_length=1000)),
                ('resim', models.CharField(max_length=50)),
                ('toplam_mac', models.IntegerField(default=0)),
                ('zafer_mac', models.IntegerField(default=0)),
                ('bozgun_mac', models.IntegerField(default=0)),
                ('cevrimici', models.BooleanField(default=False)),
            ],
        ),
    ]
