# Generated by Django 5.0 on 2023-12-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
