# Generated by Django 5.0 on 2023-12-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_engel_kisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engellenenler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engelleyen', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='engel',
            name='kisi',
        ),
        migrations.AddField(
            model_name='engel',
            name='kisi',
            field=models.ManyToManyField(blank=True, null=True, to='blog.engellenenler'),
        ),
    ]
