# Generated by Django 5.0 on 2023-12-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_kisiler_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisiler',
            name='kategori',
        ),
        migrations.AddField(
            model_name='kisiler',
            name='kategoriler',
            field=models.ManyToManyField(to='blog.kategori'),
        ),
    ]
