# Generated by Django 5.0 on 2023-12-27 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_engellenenler_remove_engel_kisi_engel_kisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='engellenenler',
            name='kisiler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kisi', to=settings.AUTH_USER_MODEL),
        ),
    ]
