# Generated by Django 5.0 on 2023-12-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_engellenenler_kisiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engellenenler',
            name='engelleyen',
            field=models.CharField(max_length=200),
        ),
    ]
