# Generated by Django 5.0 on 2023-12-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_kisiler_user_alter_kisiler_kategoriler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisiler',
            name='resim',
            field=models.ImageField(default='/static/images/blog/img/7.jpg', upload_to='blogs'),
        ),
    ]
