# Generated by Django 5.0 on 2023-12-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_engellenenler_engelleyen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engel',
            name='kisi',
        ),
        migrations.DeleteModel(
            name='Engellenenler',
        ),
    ]
