# Generated by Django 5.0 on 2023-12-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_kisiler_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisiler',
            name='kategoriler',
        ),
        migrations.AlterField(
            model_name='kisiler',
            name='resim',
            field=models.ImageField(blank=True, default='blogs/7.jpg', upload_to='blogs'),
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
