# Generated by Django 5.0 on 2023-12-21 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_relationship_ekle_alter_relationship_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisiler',
            name='friends',
        ),
        migrations.CreateModel(
            name='Arkadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diger_users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sahip', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
