# Generated by Django 5.0 on 2023-12-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
    ]
