# Generated by Django 5.0 on 2023-12-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_arkadas_diger_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisiler',
            name='engel',
        ),
        migrations.AddField(
            model_name='arkadas',
            name='engel',
            field=models.BooleanField(default=False),
        ),
    ]
