# Generated by Django 5.0 on 2023-12-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_kisiler_arkadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisiler',
            name='arkadas',
        ),
        migrations.AddField(
            model_name='kisiler',
            name='arkadas',
            field=models.ManyToManyField(to='blog.arkadas'),
        ),
    ]
