# Generated by Django 5.0 on 2023-12-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_remove_kisiler_arkadas_kisiler_arkadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisiler',
            name='arkadas',
        ),
    ]
