# Generated by Django 5.0 on 2023-12-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_remove_kisiler_user_kisiler_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisiler',
            name='arkadas',
            field=models.ManyToManyField(to='blog.arkadas'),
        ),
    ]
