# Generated by Django 5.0 on 2023-12-25 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_rename_users_kisiler_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisiler',
            name='user',
        ),
        migrations.AddField(
            model_name='kisiler',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kullanıcı', to=settings.AUTH_USER_MODEL),
        ),
    ]
