# Generated by Django 5.0 on 2023-12-25 22:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_remove_kisiler_arkadas_alter_kisiler_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisiler',
            name='id',
        ),
        migrations.AddField(
            model_name='kisiler',
            name='arkadas_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.arkadas'),
            preserve_default=False,
        ),
    ]
