# Generated by Django 4.2.7 on 2023-12-03 15:55

# import ckeditor.fields
from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            # field=ckeditor.fields.RichTextField(),
            field=models.TextField(),
        ),
    ]
