# Generated by Django 5.0 on 2023-12-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_delete_room_remove_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
